export const SET_CATEGORY = "SET_CATEGORY";
export const SET_ALL_PRODUCT = "SET_SHOWALL_PRODUCT";
export const SET_PRODUCT_BY_CATEGORY = "SET_PRODUCT_BY_CATEGORY";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const LOADING = "LOADING";
export const TOTAL = "TOTAL";
